name: test

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, macos-15, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: System info
        run: |
          echo "OS Version: $(sw_vers -productVersion)"
          echo "Locale: $(locale)"
          echo "wchar_t size: $(printf '#include <stdio.h>\n#include <wchar.h>\nint main(void) { printf(\"%zu\", sizeof(wchar_t)); return 0; }\n' | clang -x c - -o /tmp/test && /tmp/test)"

      - name: Install dependencies
        run: brew install scons mingw-w64 zlib

      - name: Install CppUnit
        run: |
          curl --retry 9 -sLo cppunit.rb "https://sourceforge.net/p/nsis/code/HEAD/tree/web-scripts/trunk/cppunit.rb?format=raw"
          HOMEBREW_DEVELOPER=true brew install -s --formula cppunit.rb
          #brew search cppunit@1.13.2

      - name: Prepare zlib directory
        run: |
          curl --retry 9 -sLo $HOME/zlib.zip "https://downloads.sourceforge.net/project/libpng/zlib/1.2.8/zlib128-dll.zip?r=&ts=1403402496&use_mirror=hivelocity"
          mkdir -p $HOME/zlib
          unzip -o $HOME/zlib.zip -d $HOME/zlib

      - name: Run scons (allow failure)
        continue-on-error: true
        run: scons ZLIB_W32=$HOME/zlib SKIPUTILS="NSIS Menu" NSIS_CONFIG_LOG=yes APPEND_CPPPATH=/opt/homebrew/include APPEND_LIBPATH=/opt/homebrew/lib test dist-zip

      - name: Print config.log
        if: always()
        run: |
          if [ -f config.log ]; then
            cat config.log
          else
            echo "config.log not found"
          fi
